### ISSUE TITLE
 cannot access org.openqa.selenium.WrapsDriver   class file for org.openqa.selenium.WrapsDriver not found

### ISSUE THREAD

**Issue by mahsanasseri** [sskorol/webdriver-supplier#23]
I am new in Appium 
I am going to test a simple notification allow but I have this error:

IDE: inteliJ IDEA 
maven project
Error:(43, 101) java: cannot access org.openqa.selenium.WrapsDriver
  class file for org.openqa.selenium.WrapsDriver not found:

I copied all dependencies: 

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>KKtest01</groupId>
    <artifactId>KKtest01</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.14.3</version>
            <scope>test</scope>
        </dependency>

        
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.3.0-RC1</version>
            <scope>test</scope>
        </dependency>

        
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>6.1.0</version>
        </dependency>
        
        

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-remote-driver</artifactId>
            <version>3.14.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-remote-driver</artifactId>
            <version>3.14.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-remote-driver</artifactId>
            <version>3.14.0</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.14.0</version>

        </dependency>
        
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>3.14.0</version>
        </dependency>

    </dependencies>

</project>`
 This is my java class for test: 

`import io.appium.java_client.AppiumDriver;
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;
import org.openqa.selenium.By;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.net.MalformedURLException;
import java.net.URL;
public class KKtest01 {

    public AppiumDriver<MobileElement> driver;
    public WebDriverWait wait;

      @BeforeMethod
    public void setup () throws MalformedURLException {
        DesiredCapabilities caps = new DesiredCapabilities();
        caps.setCapability("deviceName", "Xiaomi Mi A1");
        caps.setCapability("udid", "0eebac319805"); //DeviceId from "adb devices" command
        caps.setCapability("platformName", "Android");
        caps.setCapability("platformVersion", "8.1.0");
        caps.setCapability("skipUnlock","true");
        caps.setCapability("appPackage", "com.google.android.deskclock");
        caps.setCapability("appActivity","com.android.deskclock.DeskClock");
        caps.setCapability("noReset","false");
        driver = new AndroidDriver<MobileElement>(new URL("http://0.0.0.0:4723/wd/hub"),caps);
        wait = new WebDriverWait(driver, 10);
    }

    @Test
    public void basicTest () throws InterruptedException {

        //Notification Allow
        if (driver.findElements(By.id("com.android.packageinstaller:id/permission_allow_button")).size()>0) {
        driver.findElements(By.id("com.android.packageinstaller:id/permission_allow_button")).get(0).click();
    }`

line 43 which shows the error : `driver.findElements(By.id("com.android.packageinstaller:id/permission_allow_button")).get(0).click();

`
please help me with this
Thanks

**Comment by sskorol** [comment]
@mahsanasseri how this issue is related to `webdriver-supplier` library?.. I don't even see it in dependencies list... moreover, it was designed for web... and you're testing mobile apps...

**Comment by mahsanasseri** [comment]
I am so sorry. could you help me where should I raise my problem? thank you

**Comment by sskorol** [comment]
@mahsanasseri try https://discuss.appium.io

**Comment by mahsanasseri** [comment]
thanks
